name: CI/CD Pipeline

on:
  push:
    branches: ['*']

jobs:
  client:
    name: Client Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install dependencies
        working-directory: client
        run: npm ci
      - name: Run tests
        working-directory: client
        run: npm run test:unit
      - name: Type check
        working-directory: client
        run: npm run type-check
      - name: Build
        working-directory: client
        run: npm run build

  server:
    name: Server Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23.11.0
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
      - name: Install dependencies
        working-directory: server
        run: npm ci
      - name: Run tests
        working-directory: server
        run: npm test
      - name: Build
        working-directory: server
        run: npm run build || echo "No build script found, skipping"